version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sparkyroll_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/sparkyroll_db
      SECRET_KEY: tu_clave_secreta_super_segura_para_practica_calificada
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data: 